In [1]:
a = [1.0, 2.0, 1.0]

In [2]:
a[0]

1.0

In [4]:
a[2]=3.0
a

[1.0, 2.0, 3.0]

In [5]:
import torch 

a=torch.ones(3)

a

tensor([1., 1., 1.])

In [6]:
a[1]

tensor(1.)

In [7]:
float(a[1])

1.0

In [8]:
a[2]=2.0 

In [9]:
points=torch.zeros(6)
points

tensor([0., 0., 0., 0., 0., 0.])

In [10]:
points[0]=4.0 
points[1]=1.0 
points[2]=3.0 
points[3]=2.0 
points[4]=0.0 
points[5]=5.0

points

tensor([4., 1., 3., 2., 0., 5.])

In [11]:
points=torch.tensor([4.0,1.0,3.0,2.0,0.0,5.0])
points

tensor([4., 1., 3., 2., 0., 5.])

In [14]:
float(points[0]),float(points[1])

(4.0, 1.0)

In [16]:
points=torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [17]:
points.shape

torch.Size([3, 2])

In [18]:
points=torch.zeros(3,2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [19]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [20]:
points[0,1]

tensor(1.)

In [21]:
points[0]

tensor([4., 1.])

In [22]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.storage()

C:\Users\DC\AppData\Local\Temp\ipykernel_964\2923139482.py:2: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points.storage()


 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [23]:
points_storage=points.storage()
points_storage[0]

4.0

In [24]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_storage=points.storage()
points_storage[0]=2.0
points

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

In [25]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point=points[1]
second_point.storage_offset()

2

In [26]:
second_point.size()

torch.Size([2])

In [27]:
second_point.shape

torch.Size([2])

In [28]:
points.stride()

(2, 1)