In [3]:
a = [1.0, 2.0, 1.0]

In [4]:
a[0]

1.0

In [5]:
a[2]=3.0
a

[1.0, 2.0, 3.0]

In [6]:
import torch 

a=torch.ones(3)

a

tensor([1., 1., 1.])

In [7]:
a[1]

tensor(1.)

In [8]:
float(a[1])

1.0

In [10]:
a[2]=2.0 

In [9]:
points=torch.zeros(6)
points

tensor([0., 0., 0., 0., 0., 0.])

In [11]:
points[0]=4.0 
points[1]=1.0 
points[2]=3.0 
points[3]=2.0 
points[4]=0.0 
points[5]=5.0

points

tensor([4., 1., 3., 2., 0., 5.])

In [12]:
points=torch.tensor([4.0,1.0,3.0,2.0,0.0,5.0])
points

tensor([4., 1., 3., 2., 0., 5.])

In [13]:
float(points[0]),float(points[1])

(4.0, 1.0)

In [14]:
points=torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [15]:
points.shape

torch.Size([3, 2])

In [16]:
points=torch.zeros(3,2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [17]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [18]:
points[0,1]

tensor(1.)

In [19]:
points[0]

tensor([4., 1.])

In [20]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.storage()

C:\Users\DC\AppData\Local\Temp\ipykernel_8944\2923139482.py:2: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points.storage()


 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [21]:
points_storage=points.storage()
points_storage[0]

4.0

In [22]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_storage=points.storage()
points_storage[0]=2.0
points

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

In [23]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point=points[1]
second_point.storage_offset()

2

In [24]:
second_point.size()

torch.Size([2])

In [25]:
second_point.shape

torch.Size([2])

In [26]:
points.stride()

(2, 1)

In [27]:
second_point=points[1]
second_point.size()

torch.Size([2])

In [28]:
second_point.stride()

(1,)

In [31]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point=points[1]
second_point[0]=10.0 
points

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

In [32]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point=points[1].clone()
second_point[0]=10.0 
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [34]:
points_t=points.t() 
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [35]:
id(points.storage())== id(points_t.storage())

True

In [36]:
points.stride()

(2, 1)

In [37]:
points_t.stride()

(1, 2)

In [38]:
some_t=torch.ones(3,4,5)
transpose_t=some_t.transpose(0,2)
some_t.shape

torch.Size([3, 4, 5])

In [39]:
transpose_t.shape

torch.Size([5, 4, 3])

In [40]:
some_t.stride()

(20, 5, 1)

In [41]:
transpose_t.stride()

(1, 5, 20)

In [43]:
some_t=torch.ones(3,4,5)
transpose_t=some_t.transpose(0,2) 

some_t.shape

torch.Size([3, 4, 5])

In [44]:
transpose_t.shape

torch.Size([5, 4, 3])

In [45]:
transpose_t.shape

torch.Size([5, 4, 3])

In [47]:
transpose_t.stride()

(1, 5, 20)

In [46]:
some_t.stride()

(20, 5, 1)

In [49]:
points.is_contiguous()

True

In [50]:
points_t.is_contiguous()

False

In [51]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]]) 
points_t=points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [52]:
points_t.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [53]:
points_t.stride()

(1, 2)

In [54]:
points_t_count=points_t.contiguous()
points_t_count

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [55]:
points_t_count.storage()

 4.0
 5.0
 2.0
 1.0
 3.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [58]:
double_Points=torch.ones(10,2,dtype=torch.double)
short_points=torch.tensor([[1,2],[3,4]],dtype=torch.short)
short_points.dtype

torch.int16

In [59]:
double_points=torch.zeros(10,2).double()
short_points=torch.ones(10,2).short()

In [60]:
double_points=torch.zeros(10,2).double().to(torch.double)
short_points=torch.ones(10,2).short().to(dtype=torch.short)

In [61]:
points_64=torch.rand(5,dtype=torch.double)
points_short=points_64.to(torch.short)
points_64 * points_short 

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

In [62]:
points=torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])

In [63]:
some_list=list(range(6))
some_list[:]
some_list[1:4]
some_list[1:]
some_list[:4]
some_list[:-1]
some_list[1:4:2]

[1, 3]

In [64]:
points[1:]       # <1>
points[1:, :]    # <2>
points[1:, 0]    # <3>
points[None]     # <4>

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

In [65]:
points=torch.ones(3,4)
points_np=points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [67]:
points=torch.from_numpy(points_np)
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [68]:
torch.save(points,'../data/p1ch3/ourpoints.t')

In [69]:
with open('../data/p1ch3/outpoints.t','wb') as f :

    torch.save(points,f)

In [70]:
points=torch.load('../data/p1ch3/outpoints.t')

In [74]:
with open('../data/p1ch3/ourpoints.t','rb') as f:
   points = torch.load(f)

In [75]:
#The h5py package is a Pythonic interface to the HDF5 binary data format.

import h5py 

f=h5py.File('../data/p1ch3/outpoints.t','w') 
dset=f.create_dataset('coords',data=points.numpy())
f.close()

   

In [77]:
f=h5py.File('../data/p1ch3/outpoints.t','r') 
dset=f['coords']
last_points = dset[-2:]

In [78]:
last_points=torch.from_numpy(dset[-2:])
f.close()

In [80]:
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [82]:
#points_gpu=points.to(device='cuda')
#points_gpu = points.to(device='cuda:0')

In [85]:
#points_gpu = points.cuda()  # <1>

points_cpu = points_gpu.cpu()

In [92]:
#points_gpu = points_gpu.to(device='cuda')

In [94]:
points=2*points 

#points_gpu=2*points.to(device='cuda')

points_gpu = points_gpu + 4

In [95]:
a=torch.ones(3,2)
a_T=torch.transpose(a,0,1)

a.shape,a.transpose 

(torch.Size([3, 2]), <function Tensor.transpose>)

In [96]:
a = torch.ones(3, 2)
a_t = a.transpose(0, 1)

a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))